@baseUrl= https://ladangxadmin.upplex.com.my
# @token= 115|AZ1q3EtwRD4YThjqYh1NmHz5XVweUy9laIacMQpi
@token = 130|JZUvY23I70u0aUccHB6cQh2EZwAFkBU98cPEabTN
@token2= 4|3tNUf4GvnzFHJfgwUAvI48FnqfI4L5umXd7faJFn


###
POST {{baseUrl}}/api/v1/otp/resend
Content-Type: application/json
Accept: application/json

{
  "identifier": "eyJpdiI6IkZrS0lKWmoxZ1lDa0JJbmQwckRDbWc9PSIsInZhbHVlIjoiZG9BWE50R1JmWkFWSmZlZi9WZ050QT09IiwibWFjIjoiZDQ5YzZhNTdjNDhhOGYxMDhiN2QwM2ViZGNkNWFlNjM5YTk2YjBmYWU5M2FhZTFiNzg0ZDk2M2IxNTAyNGE1ZiIsInRhZyI6IiJ9",
  "phone_number":"123123122",
  "email":"ab@aac.com",
  "fullname":"123",
  "password":"123123123",
  "password_confirmation":"123123123",
  "request_type": 1
}

###
GET {{baseUrl}}/api/v1/visits/v2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}



###

POST {{baseUrl}}/api/v1/visits/cart/add
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "visit_date":"2026-02-25",
  "details":[]
}

###

PUT {{baseUrl}}/api/v1/visits/cart/update
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "details":[
    {
      "ticket_type_id":"ow",
      "quantity":2
    }
  ]
}


###
GET {{baseUrl}}/api/v1/visits
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


###

GET {{baseUrl}}/api/v1/user-quizzes
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}



###
GET {{baseUrl}}/api/v1/user-quizzes/check-all-completed
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


###

POST {{baseUrl}}/api/v1/user-quizzes/start
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "field_item_id":2
}

###
GET {{baseUrl}}/api/v1/user-quizzes/answers-by-type
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "user_quiz_id":4
}

###

GET {{baseUrl}}/api/v1/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token2}}

###

GET {{baseUrl}}/api/v1/vouchers
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token2}}

{
  "per_page":10,
  "page":1
}

###

GET {{baseUrl}}/api/v1/visits/cart
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/api/v1/vouchers/validate
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "cart":"xQg",
  "promo_code":"B2F1AD"
}
